apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-pod-rightsizer
  namespace: rightsizer-system
  labels:
    app.kubernetes.io/name: kube-pod-rightsizer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-pod-rightsizer
  labels:
    app.kubernetes.io/name: kube-pod-rightsizer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-pod-rightsizer
  labels:
    app.kubernetes.io/name: kube-pod-rightsizer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-pod-rightsizer
subjects:
  - kind: ServiceAccount
    name: kube-pod-rightsizer
    namespace: rightsizer-system
