apiVersion: v1
kind: Service
metadata:
  name: kube-pod-rightsizer
  namespace: kube-pod-rightsizer
  labels:
    app.kubernetes.io/name: kube-pod-rightsizer
spec:
  selector:
    app.kubernetes.io/name: kube-pod-rightsizer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
